### ISSUE TITLE
Pages have no content

### ISSUE THREAD

**Issue by Aldekein** [ethereum/verkle-dev-website#10]
Hey @kevaundray 

I noticed the pages at website sometimes have empty content. For example https://verkle.dev/impl/eip.html should probably display https://github.com/ethereum/verkle-dev-website/blob/master/docs/Implementation/eip.md but it shows empty page with just a header.

https://verkle.dev/why_verkle_trie.html is another example.

**Comment by kevaundray** [comment]
Think this has to do with the CI not generating the new content for gh-pages. 

It is still showing mdbook generated content, will need to explore why docusaurus is not being built from the CI

**Comment by kevaundray** [comment]
This should now be fixed. 

Also added the CNAME file to the static folder, so it does not need to be copied onto the gh-pages branch each time we rebuild

**Comment by Aldekein** [comment]
Great job! Can confirm the pages now are actual. 

But I noticed a bug. There's an "[Edit this page]" link below each article. It leads to "Not Found" page.

**Comment by kevaundray** [comment]
Great spot :) Should be fixed now!

**Comment by Aldekein** [comment]
Confirming. And one more display bug, now fith formulae:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/671454/192617829-50160426-5973-4027-a0d7-41fd0d212208.png">
https://verkle.dev/docs/Theory/dividing_on_zero

**Comment by kevaundray** [comment]
Ooof thats a strange one, @JEAlfonsoP if you have time can you look into why the formulae are not rendering?

**Comment by JEAlfonsoP** [comment]
> Ooof thats a strange one, @JEAlfonsoP if you have time can you look into why the formulae are not rendering?

I will take a look on it.

**Comment by JEAlfonsoP** [comment]
Hi, I hope this help to fix this bug: (Mathematical equations can be rendered using KaTeX).

@kevaundray  if you like please introduce me to the person testing and building the web, so I can help with the testing either. 

deploy.yml

yarn add remark-math@3 rehype-katex@5 hast-util-is-element@1.1.0

docusaurus.config.js

const math = require('remark-math');
const katex = require('rehype-katex');

module.exports = {
  title: 'Docusaurus',
  tagline: 'Build optimized websites quickly, focus on your content',
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          path: 'docs',
          remarkPlugins: [math],
          rehypePlugins: [katex],
        },
      },
    ],
  ],
  stylesheets: [
    {
      href: 'https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css',
      type: 'text/css',
      integrity:
        'sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM',
      crossorigin: 'anonymous',
    },
  ],
};

module.exports = createConfig;

**Comment by kevaundray** [comment]
@JEAlfonsoP the website is automatically rebuilt by the CI, so you only need to make a PR with those changes.

For testing, can you see if it works locally? The part where you add new dependencies using yarn should be quite straightforward to add to the deploy.yml file

**Comment by JEAlfonsoP** [comment]
Ok. I will add the changes and will test those in my local environment in order to PR.

**Comment by kevaundray** [comment]
Closing as all issues seem to be fixed now
