### ISSUE TITLE
Formulas not being rendered correctly 

### ISSUE THREAD

**Issue by ndrozd** [ethereum/verkle-dev-website#12]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/6696080/192172979-821b64ed-79ca-4356-88d5-98a887acd4fa.png">

**Comment by kevaundray** [comment]
Thanks for flagging this. This has also been flagged here: https://github.com/ethereum/verkle-dev-website/issues/10#issuecomment-1259954263

Will leave this issue open to track

**Comment by kevaundray** [comment]
This should now be fixed via or #14
