### ISSUE TITLE
Wrong links in a sidebar for pages with ( or ) in title

### ISSUE THREAD

**Issue by ndrozd** [ethereum/verkle-dev-website#13]
Link in sidebar – https://verkle.dev/docs/Theory/Math/connectivity%20(graph%20theory)
Actual page URL – https://verkle.dev/docs/Theory/Math/connectivity%20graph%20theory

**Comment by ndrozd** [comment]
Probably a docusaurus issue

**Comment by kevaundray** [comment]
As mentioned in the referenced PR, since this is a docusaurus issue, we will not use brackets in titles as a mitigation
